appenders = console

rootLogger.level = error
rootLogger.appenderRef.console.ref = Console

appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %p %c{1}: %m%n