appenders = console

appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %p %c{1}: %m%n

appender.console.filter.range.type = LevelRangeFilter
appender.console.filter.range.minLevel = info
appender.console.filter.range.maxLevel = info
appender.console.filter.range.onMatch = accept
appender.console.filter.range.onMismatch = deny

rootLogger.level = info
rootLogger.appenderRef.console.ref = Console